// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbzq-eOAIjsRzVgMPht_klnCvWZJ_Sh7M',
    appId: '1:255234684675:web:162148c03e3e4ef7441b36',
    messagingSenderId: '255234684675',
    projectId: 'carsave-61b20',
    authDomain: 'carsave-61b20.firebaseapp.com',
    storageBucket: 'carsave-61b20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVYR6r-Q7sdH20HKl9rWRlQS-jbvleYc',
    appId: '1:255234684675:android:fa72bc6bb6ccc2bc441b36',
    messagingSenderId: '255234684675',
    projectId: 'carsave-61b20',
    storageBucket: 'carsave-61b20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeB0rFgFshSdYEkNcCAoL84IFa_m5-TcI',
    appId: '1:255234684675:ios:5b7e6d65681a9fea441b36',
    messagingSenderId: '255234684675',
    projectId: 'carsave-61b20',
    storageBucket: 'carsave-61b20.appspot.com',
    iosBundleId: 'com.example.carsave',
  );
}
